spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EduSmartDB;encrypt=false
spring.datasource.username=sa
spring.datasource.password=NuevaClave123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Configuración para respetar nombres exactos de tablas y columnas
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server.port=8081